allowBuilds:
  '@larksuite/cli': true
  esbuild: true
  sharp: true
  unrs-resolver: true
autoInstallPeers: true
dedupePeerDependents: true
ignorePnpmfile: true
onlyBuiltDependencies:
  - "@larksuite/cli"
  - "@parcel/watcher"
  - "@swc/core"
  - "esbuild"
  - "msw"
  - "sharp"
  - "unrs-resolver"
preferWorkspacePackages: true
resolutionMode: highest
strictPeerDependencies: false
useLockfile: true
verifyStoreIntegrity: false
